import { ref } from "vue";
import { supabase } from "../supabase";

export function useProductsList() {
  const rows = ref(10);
  const rowsPerPageOptions = ref([10, 20, 50, 100, 200]);

  const products = ref([]);
  const selectedProduct = ref(null);

  const loading = ref(false);
  const error = ref(null);
  const searchValue = ref("");
  const showDialog = ref(false);
  const dialogData = ref(null);

  const fetchProducts = async () => {
    loading.value = true;
    error.value = null;

    try {
      const sv = searchValue.value?.trim() || "";

      let query = supabase
        .from("products")
        .select("*")
        .order("category", { ascending: true })
        .order("code", { ascending: true });

      if (sv) {
        query = query.or(`code.ilike.%${sv}%,category.ilike.%${sv}%`);
      }

      const { data, error: fetchError } = await query;

      if (fetchError) {
        // console.error("Error fetching products:", fetchError);
        // error.value = "Failed to load products.";

        throw fetchError;
      }
      products.value = data ?? [];
    } catch (err) {
      console.error("Error fetching products:", err);

      error.value = err?.message || "Failed to load products.";
      products.value = [];
    } finally {
      loading.value = false;
    }
  };

  const saveProduct = async (id, category, code, weight, price, unit, image_url) => {
    loading.value = true;
    error.value = null;

    try {
      const productId = String(id ?? "").trim();

      const payload = {
        category: category?.trim(),
        code: code?.trim(),
        weight: Number(weight),
        price: Number(price),
        unit: unit?.trim(),
        image_url: image_url?.trim() || null,
      };

      console.log({
        id: productId,
        category: payload.category,
        code: payload.code,
        weight: payload.weight,
        price: payload.price,
        unit: payload.unit,
        image_url: payload.image_url,
      });

      let query;

      if (productId === "") {
        // CREATE: ID is generated by the database
        query = supabase.from("products").insert(payload).select().single();
      } else {
        // UPDATE: update the product matching this ID
        query = supabase.from("products").update(payload).eq("id", productId).select().single();
      }

      const { data, error: saveError } = await query;

      if (saveError) {
        throw saveError;
      }

      // Reload to preserve category/code sorting
      await fetchProducts();

      return data;
    } catch (err) {
      console.error("Save product error:", err);
      error.value = err?.message || "Failed to save product.";
      throw err;
    } finally {
      loading.value = false;
    }
  };

  const onRowClick = (event) => {
    const clickedProduct = event?.data;

    if (!clickedProduct) {
      return;
    }

    if (selectedProduct.value?.id === clickedProduct.id) {
      selectedProduct.value = null;
      dialogData.value = null;
      showDialog.value = false;
      return;
    }

    selectedProduct.value = clickedProduct;
    dialogData.value = clickedProduct;
    showDialog.value = true;
  };

  const fetchProductById = async (id) => {
    if (!id) {
      return null;
    }

    loading.value = true;
    error.value = null;

    try {
      const { data, error: fetchError } = await supabase
        .from("products")
        .select("*")
        .eq("id", id)
        .single();

      if (fetchError) {
        throw fetchError;
      }

      return data;
    } catch (err) {
      console.error("Error fetching product:", err);

      error.value = err?.message || "Failed to load product.";
      throw err;
    } finally {
      loading.value = false;
    }
  };

  const deleteProduct = async (id) => {
    const productId = String(id ?? "").trim();

    if (!productId) {
      throw new Error("Product ID is required.");
    }

    loading.value = true;
    error.value = null;

    try {
      const { error: deleteError } = await supabase.from("products").delete().eq("id", productId);

      if (deleteError) {
        throw deleteError;
      }

      // Remove it immediately from the displayed list
      products.value = products.value.filter((product) => String(product.id) !== productId);

      // Clear selection/dialog if the deleted product was selected
      if (String(selectedProduct.value?.id) === productId) {
        selectedProduct.value = null;
        dialogData.value = null;
        showDialog.value = false;
      }

      return true;
    } catch (err) {
      console.error("Delete product error:", err);
      error.value = err?.message || "Failed to delete product.";
      throw err;
    } finally {
      loading.value = false;
    }
  };

  return {
    rows,
    rowsPerPageOptions,
    products,
    selectedProduct,
    loading,
    error,
    searchValue,

    fetchProducts,
    fetchProductById,
    saveProduct,
    deleteProduct,
    showDialog,
    dialogData,
    onRowClick,
  };
}
